###################################################################

# Created by write_sdc on Mon May 18 10:51:33 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max WCCOM -max_library                               \
fsa0m_a_generic_core_ss1p62v125c\
                         -min BCCOM -min_library                               \
fsa0m_a_generic_core_ff1p98vm40c
set_wire_load_mode top
set_wire_load_model -name enG30K -library fsa0m_a_generic_core_ss1p62v125c
set_load -pin_load 0.05 [get_ports inf_out_valid]
set_load -pin_load 0.05 [get_ports {inf_warn_msg[2]}]
set_load -pin_load 0.05 [get_ports {inf_warn_msg[1]}]
set_load -pin_load 0.05 [get_ports {inf_warn_msg[0]}]
set_load -pin_load 0.05 [get_ports inf_complete]
set_load -pin_load 0.05 [get_ports inf_AR_VALID]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[16]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[15]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[14]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[13]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[12]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[11]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[10]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[9]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[8]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[7]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[6]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[5]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[4]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[3]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[2]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[1]}]
set_load -pin_load 0.05 [get_ports {inf_AR_ADDR[0]}]
set_load -pin_load 0.05 [get_ports inf_R_READY]
set_load -pin_load 0.05 [get_ports inf_AW_VALID]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[16]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[15]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[14]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[13]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[12]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[11]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[10]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[9]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[8]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[7]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[6]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[5]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[4]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[3]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[2]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[1]}]
set_load -pin_load 0.05 [get_ports {inf_AW_ADDR[0]}]
set_load -pin_load 0.05 [get_ports inf_W_VALID]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[63]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[62]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[61]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[60]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[59]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[58]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[57]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[56]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[55]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[54]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[53]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[52]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[51]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[50]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[49]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[48]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[47]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[46]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[45]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[44]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[43]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[42]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[41]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[40]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[39]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[38]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[37]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[36]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[35]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[34]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[33]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[32]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[31]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[30]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[29]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[28]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[27]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[26]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[25]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[24]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[23]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[22]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[21]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[20]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[19]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[18]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[17]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[16]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[15]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[14]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[13]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[12]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[11]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[10]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[9]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[8]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[7]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[6]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[5]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[4]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[3]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[2]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[1]}]
set_load -pin_load 0.05 [get_ports {inf_W_DATA[0]}]
set_load -pin_load 0.05 [get_ports inf_B_READY]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports inf_rst_n]
set_max_capacitance 0.15 [get_ports inf_sel_action_valid]
set_max_capacitance 0.15 [get_ports inf_type_valid]
set_max_capacitance 0.15 [get_ports inf_mode_valid]
set_max_capacitance 0.15 [get_ports inf_date_valid]
set_max_capacitance 0.15 [get_ports inf_staff_valid]
set_max_capacitance 0.15 [get_ports inf_data_no_valid]
set_max_capacitance 0.15 [get_ports inf_restock_valid]
set_max_capacitance 0.15 [get_ports {inf_D[71]}]
set_max_capacitance 0.15 [get_ports {inf_D[70]}]
set_max_capacitance 0.15 [get_ports {inf_D[69]}]
set_max_capacitance 0.15 [get_ports {inf_D[68]}]
set_max_capacitance 0.15 [get_ports {inf_D[67]}]
set_max_capacitance 0.15 [get_ports {inf_D[66]}]
set_max_capacitance 0.15 [get_ports {inf_D[65]}]
set_max_capacitance 0.15 [get_ports {inf_D[64]}]
set_max_capacitance 0.15 [get_ports {inf_D[63]}]
set_max_capacitance 0.15 [get_ports {inf_D[62]}]
set_max_capacitance 0.15 [get_ports {inf_D[61]}]
set_max_capacitance 0.15 [get_ports {inf_D[60]}]
set_max_capacitance 0.15 [get_ports {inf_D[59]}]
set_max_capacitance 0.15 [get_ports {inf_D[58]}]
set_max_capacitance 0.15 [get_ports {inf_D[57]}]
set_max_capacitance 0.15 [get_ports {inf_D[56]}]
set_max_capacitance 0.15 [get_ports {inf_D[55]}]
set_max_capacitance 0.15 [get_ports {inf_D[54]}]
set_max_capacitance 0.15 [get_ports {inf_D[53]}]
set_max_capacitance 0.15 [get_ports {inf_D[52]}]
set_max_capacitance 0.15 [get_ports {inf_D[51]}]
set_max_capacitance 0.15 [get_ports {inf_D[50]}]
set_max_capacitance 0.15 [get_ports {inf_D[49]}]
set_max_capacitance 0.15 [get_ports {inf_D[48]}]
set_max_capacitance 0.15 [get_ports {inf_D[47]}]
set_max_capacitance 0.15 [get_ports {inf_D[46]}]
set_max_capacitance 0.15 [get_ports {inf_D[45]}]
set_max_capacitance 0.15 [get_ports {inf_D[44]}]
set_max_capacitance 0.15 [get_ports {inf_D[43]}]
set_max_capacitance 0.15 [get_ports {inf_D[42]}]
set_max_capacitance 0.15 [get_ports {inf_D[41]}]
set_max_capacitance 0.15 [get_ports {inf_D[40]}]
set_max_capacitance 0.15 [get_ports {inf_D[39]}]
set_max_capacitance 0.15 [get_ports {inf_D[38]}]
set_max_capacitance 0.15 [get_ports {inf_D[37]}]
set_max_capacitance 0.15 [get_ports {inf_D[36]}]
set_max_capacitance 0.15 [get_ports {inf_D[35]}]
set_max_capacitance 0.15 [get_ports {inf_D[34]}]
set_max_capacitance 0.15 [get_ports {inf_D[33]}]
set_max_capacitance 0.15 [get_ports {inf_D[32]}]
set_max_capacitance 0.15 [get_ports {inf_D[31]}]
set_max_capacitance 0.15 [get_ports {inf_D[30]}]
set_max_capacitance 0.15 [get_ports {inf_D[29]}]
set_max_capacitance 0.15 [get_ports {inf_D[28]}]
set_max_capacitance 0.15 [get_ports {inf_D[27]}]
set_max_capacitance 0.15 [get_ports {inf_D[26]}]
set_max_capacitance 0.15 [get_ports {inf_D[25]}]
set_max_capacitance 0.15 [get_ports {inf_D[24]}]
set_max_capacitance 0.15 [get_ports {inf_D[23]}]
set_max_capacitance 0.15 [get_ports {inf_D[22]}]
set_max_capacitance 0.15 [get_ports {inf_D[21]}]
set_max_capacitance 0.15 [get_ports {inf_D[20]}]
set_max_capacitance 0.15 [get_ports {inf_D[19]}]
set_max_capacitance 0.15 [get_ports {inf_D[18]}]
set_max_capacitance 0.15 [get_ports {inf_D[17]}]
set_max_capacitance 0.15 [get_ports {inf_D[16]}]
set_max_capacitance 0.15 [get_ports {inf_D[15]}]
set_max_capacitance 0.15 [get_ports {inf_D[14]}]
set_max_capacitance 0.15 [get_ports {inf_D[13]}]
set_max_capacitance 0.15 [get_ports {inf_D[12]}]
set_max_capacitance 0.15 [get_ports {inf_D[11]}]
set_max_capacitance 0.15 [get_ports {inf_D[10]}]
set_max_capacitance 0.15 [get_ports {inf_D[9]}]
set_max_capacitance 0.15 [get_ports {inf_D[8]}]
set_max_capacitance 0.15 [get_ports {inf_D[7]}]
set_max_capacitance 0.15 [get_ports {inf_D[6]}]
set_max_capacitance 0.15 [get_ports {inf_D[5]}]
set_max_capacitance 0.15 [get_ports {inf_D[4]}]
set_max_capacitance 0.15 [get_ports {inf_D[3]}]
set_max_capacitance 0.15 [get_ports {inf_D[2]}]
set_max_capacitance 0.15 [get_ports {inf_D[1]}]
set_max_capacitance 0.15 [get_ports {inf_D[0]}]
set_max_capacitance 0.15 [get_ports inf_AR_READY]
set_max_capacitance 0.15 [get_ports inf_R_VALID]
set_max_capacitance 0.15 [get_ports {inf_R_RESP[1]}]
set_max_capacitance 0.15 [get_ports {inf_R_RESP[0]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[63]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[62]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[61]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[60]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[59]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[58]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[57]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[56]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[55]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[54]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[53]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[52]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[51]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[50]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[49]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[48]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[47]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[46]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[45]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[44]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[43]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[42]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[41]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[40]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[39]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[38]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[37]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[36]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[35]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[34]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[33]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[32]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[31]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[30]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[29]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[28]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[27]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[26]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[25]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[24]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[23]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[22]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[21]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[20]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[19]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[18]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[17]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[16]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[15]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[14]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[13]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[12]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[11]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[10]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[9]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[8]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[7]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[6]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[5]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[4]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[3]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[2]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[1]}]
set_max_capacitance 0.15 [get_ports {inf_R_DATA[0]}]
set_max_capacitance 0.15 [get_ports inf_AW_READY]
set_max_capacitance 0.15 [get_ports inf_W_READY]
set_max_capacitance 0.15 [get_ports inf_B_VALID]
set_max_capacitance 0.15 [get_ports {inf_B_RESP[1]}]
set_max_capacitance 0.15 [get_ports {inf_B_RESP[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports inf_rst_n]
set_max_fanout 10 [get_ports inf_sel_action_valid]
set_max_fanout 10 [get_ports inf_type_valid]
set_max_fanout 10 [get_ports inf_mode_valid]
set_max_fanout 10 [get_ports inf_date_valid]
set_max_fanout 10 [get_ports inf_staff_valid]
set_max_fanout 10 [get_ports inf_data_no_valid]
set_max_fanout 10 [get_ports inf_restock_valid]
set_max_fanout 10 [get_ports {inf_D[71]}]
set_max_fanout 10 [get_ports {inf_D[70]}]
set_max_fanout 10 [get_ports {inf_D[69]}]
set_max_fanout 10 [get_ports {inf_D[68]}]
set_max_fanout 10 [get_ports {inf_D[67]}]
set_max_fanout 10 [get_ports {inf_D[66]}]
set_max_fanout 10 [get_ports {inf_D[65]}]
set_max_fanout 10 [get_ports {inf_D[64]}]
set_max_fanout 10 [get_ports {inf_D[63]}]
set_max_fanout 10 [get_ports {inf_D[62]}]
set_max_fanout 10 [get_ports {inf_D[61]}]
set_max_fanout 10 [get_ports {inf_D[60]}]
set_max_fanout 10 [get_ports {inf_D[59]}]
set_max_fanout 10 [get_ports {inf_D[58]}]
set_max_fanout 10 [get_ports {inf_D[57]}]
set_max_fanout 10 [get_ports {inf_D[56]}]
set_max_fanout 10 [get_ports {inf_D[55]}]
set_max_fanout 10 [get_ports {inf_D[54]}]
set_max_fanout 10 [get_ports {inf_D[53]}]
set_max_fanout 10 [get_ports {inf_D[52]}]
set_max_fanout 10 [get_ports {inf_D[51]}]
set_max_fanout 10 [get_ports {inf_D[50]}]
set_max_fanout 10 [get_ports {inf_D[49]}]
set_max_fanout 10 [get_ports {inf_D[48]}]
set_max_fanout 10 [get_ports {inf_D[47]}]
set_max_fanout 10 [get_ports {inf_D[46]}]
set_max_fanout 10 [get_ports {inf_D[45]}]
set_max_fanout 10 [get_ports {inf_D[44]}]
set_max_fanout 10 [get_ports {inf_D[43]}]
set_max_fanout 10 [get_ports {inf_D[42]}]
set_max_fanout 10 [get_ports {inf_D[41]}]
set_max_fanout 10 [get_ports {inf_D[40]}]
set_max_fanout 10 [get_ports {inf_D[39]}]
set_max_fanout 10 [get_ports {inf_D[38]}]
set_max_fanout 10 [get_ports {inf_D[37]}]
set_max_fanout 10 [get_ports {inf_D[36]}]
set_max_fanout 10 [get_ports {inf_D[35]}]
set_max_fanout 10 [get_ports {inf_D[34]}]
set_max_fanout 10 [get_ports {inf_D[33]}]
set_max_fanout 10 [get_ports {inf_D[32]}]
set_max_fanout 10 [get_ports {inf_D[31]}]
set_max_fanout 10 [get_ports {inf_D[30]}]
set_max_fanout 10 [get_ports {inf_D[29]}]
set_max_fanout 10 [get_ports {inf_D[28]}]
set_max_fanout 10 [get_ports {inf_D[27]}]
set_max_fanout 10 [get_ports {inf_D[26]}]
set_max_fanout 10 [get_ports {inf_D[25]}]
set_max_fanout 10 [get_ports {inf_D[24]}]
set_max_fanout 10 [get_ports {inf_D[23]}]
set_max_fanout 10 [get_ports {inf_D[22]}]
set_max_fanout 10 [get_ports {inf_D[21]}]
set_max_fanout 10 [get_ports {inf_D[20]}]
set_max_fanout 10 [get_ports {inf_D[19]}]
set_max_fanout 10 [get_ports {inf_D[18]}]
set_max_fanout 10 [get_ports {inf_D[17]}]
set_max_fanout 10 [get_ports {inf_D[16]}]
set_max_fanout 10 [get_ports {inf_D[15]}]
set_max_fanout 10 [get_ports {inf_D[14]}]
set_max_fanout 10 [get_ports {inf_D[13]}]
set_max_fanout 10 [get_ports {inf_D[12]}]
set_max_fanout 10 [get_ports {inf_D[11]}]
set_max_fanout 10 [get_ports {inf_D[10]}]
set_max_fanout 10 [get_ports {inf_D[9]}]
set_max_fanout 10 [get_ports {inf_D[8]}]
set_max_fanout 10 [get_ports {inf_D[7]}]
set_max_fanout 10 [get_ports {inf_D[6]}]
set_max_fanout 10 [get_ports {inf_D[5]}]
set_max_fanout 10 [get_ports {inf_D[4]}]
set_max_fanout 10 [get_ports {inf_D[3]}]
set_max_fanout 10 [get_ports {inf_D[2]}]
set_max_fanout 10 [get_ports {inf_D[1]}]
set_max_fanout 10 [get_ports {inf_D[0]}]
set_max_fanout 10 [get_ports inf_AR_READY]
set_max_fanout 10 [get_ports inf_R_VALID]
set_max_fanout 10 [get_ports {inf_R_RESP[1]}]
set_max_fanout 10 [get_ports {inf_R_RESP[0]}]
set_max_fanout 10 [get_ports {inf_R_DATA[63]}]
set_max_fanout 10 [get_ports {inf_R_DATA[62]}]
set_max_fanout 10 [get_ports {inf_R_DATA[61]}]
set_max_fanout 10 [get_ports {inf_R_DATA[60]}]
set_max_fanout 10 [get_ports {inf_R_DATA[59]}]
set_max_fanout 10 [get_ports {inf_R_DATA[58]}]
set_max_fanout 10 [get_ports {inf_R_DATA[57]}]
set_max_fanout 10 [get_ports {inf_R_DATA[56]}]
set_max_fanout 10 [get_ports {inf_R_DATA[55]}]
set_max_fanout 10 [get_ports {inf_R_DATA[54]}]
set_max_fanout 10 [get_ports {inf_R_DATA[53]}]
set_max_fanout 10 [get_ports {inf_R_DATA[52]}]
set_max_fanout 10 [get_ports {inf_R_DATA[51]}]
set_max_fanout 10 [get_ports {inf_R_DATA[50]}]
set_max_fanout 10 [get_ports {inf_R_DATA[49]}]
set_max_fanout 10 [get_ports {inf_R_DATA[48]}]
set_max_fanout 10 [get_ports {inf_R_DATA[47]}]
set_max_fanout 10 [get_ports {inf_R_DATA[46]}]
set_max_fanout 10 [get_ports {inf_R_DATA[45]}]
set_max_fanout 10 [get_ports {inf_R_DATA[44]}]
set_max_fanout 10 [get_ports {inf_R_DATA[43]}]
set_max_fanout 10 [get_ports {inf_R_DATA[42]}]
set_max_fanout 10 [get_ports {inf_R_DATA[41]}]
set_max_fanout 10 [get_ports {inf_R_DATA[40]}]
set_max_fanout 10 [get_ports {inf_R_DATA[39]}]
set_max_fanout 10 [get_ports {inf_R_DATA[38]}]
set_max_fanout 10 [get_ports {inf_R_DATA[37]}]
set_max_fanout 10 [get_ports {inf_R_DATA[36]}]
set_max_fanout 10 [get_ports {inf_R_DATA[35]}]
set_max_fanout 10 [get_ports {inf_R_DATA[34]}]
set_max_fanout 10 [get_ports {inf_R_DATA[33]}]
set_max_fanout 10 [get_ports {inf_R_DATA[32]}]
set_max_fanout 10 [get_ports {inf_R_DATA[31]}]
set_max_fanout 10 [get_ports {inf_R_DATA[30]}]
set_max_fanout 10 [get_ports {inf_R_DATA[29]}]
set_max_fanout 10 [get_ports {inf_R_DATA[28]}]
set_max_fanout 10 [get_ports {inf_R_DATA[27]}]
set_max_fanout 10 [get_ports {inf_R_DATA[26]}]
set_max_fanout 10 [get_ports {inf_R_DATA[25]}]
set_max_fanout 10 [get_ports {inf_R_DATA[24]}]
set_max_fanout 10 [get_ports {inf_R_DATA[23]}]
set_max_fanout 10 [get_ports {inf_R_DATA[22]}]
set_max_fanout 10 [get_ports {inf_R_DATA[21]}]
set_max_fanout 10 [get_ports {inf_R_DATA[20]}]
set_max_fanout 10 [get_ports {inf_R_DATA[19]}]
set_max_fanout 10 [get_ports {inf_R_DATA[18]}]
set_max_fanout 10 [get_ports {inf_R_DATA[17]}]
set_max_fanout 10 [get_ports {inf_R_DATA[16]}]
set_max_fanout 10 [get_ports {inf_R_DATA[15]}]
set_max_fanout 10 [get_ports {inf_R_DATA[14]}]
set_max_fanout 10 [get_ports {inf_R_DATA[13]}]
set_max_fanout 10 [get_ports {inf_R_DATA[12]}]
set_max_fanout 10 [get_ports {inf_R_DATA[11]}]
set_max_fanout 10 [get_ports {inf_R_DATA[10]}]
set_max_fanout 10 [get_ports {inf_R_DATA[9]}]
set_max_fanout 10 [get_ports {inf_R_DATA[8]}]
set_max_fanout 10 [get_ports {inf_R_DATA[7]}]
set_max_fanout 10 [get_ports {inf_R_DATA[6]}]
set_max_fanout 10 [get_ports {inf_R_DATA[5]}]
set_max_fanout 10 [get_ports {inf_R_DATA[4]}]
set_max_fanout 10 [get_ports {inf_R_DATA[3]}]
set_max_fanout 10 [get_ports {inf_R_DATA[2]}]
set_max_fanout 10 [get_ports {inf_R_DATA[1]}]
set_max_fanout 10 [get_ports {inf_R_DATA[0]}]
set_max_fanout 10 [get_ports inf_AW_READY]
set_max_fanout 10 [get_ports inf_W_READY]
set_max_fanout 10 [get_ports inf_B_VALID]
set_max_fanout 10 [get_ports {inf_B_RESP[1]}]
set_max_fanout 10 [get_ports {inf_B_RESP[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports inf_rst_n]
set_max_transition 3 [get_ports inf_sel_action_valid]
set_max_transition 3 [get_ports inf_type_valid]
set_max_transition 3 [get_ports inf_mode_valid]
set_max_transition 3 [get_ports inf_date_valid]
set_max_transition 3 [get_ports inf_staff_valid]
set_max_transition 3 [get_ports inf_data_no_valid]
set_max_transition 3 [get_ports inf_restock_valid]
set_max_transition 3 [get_ports {inf_D[71]}]
set_max_transition 3 [get_ports {inf_D[70]}]
set_max_transition 3 [get_ports {inf_D[69]}]
set_max_transition 3 [get_ports {inf_D[68]}]
set_max_transition 3 [get_ports {inf_D[67]}]
set_max_transition 3 [get_ports {inf_D[66]}]
set_max_transition 3 [get_ports {inf_D[65]}]
set_max_transition 3 [get_ports {inf_D[64]}]
set_max_transition 3 [get_ports {inf_D[63]}]
set_max_transition 3 [get_ports {inf_D[62]}]
set_max_transition 3 [get_ports {inf_D[61]}]
set_max_transition 3 [get_ports {inf_D[60]}]
set_max_transition 3 [get_ports {inf_D[59]}]
set_max_transition 3 [get_ports {inf_D[58]}]
set_max_transition 3 [get_ports {inf_D[57]}]
set_max_transition 3 [get_ports {inf_D[56]}]
set_max_transition 3 [get_ports {inf_D[55]}]
set_max_transition 3 [get_ports {inf_D[54]}]
set_max_transition 3 [get_ports {inf_D[53]}]
set_max_transition 3 [get_ports {inf_D[52]}]
set_max_transition 3 [get_ports {inf_D[51]}]
set_max_transition 3 [get_ports {inf_D[50]}]
set_max_transition 3 [get_ports {inf_D[49]}]
set_max_transition 3 [get_ports {inf_D[48]}]
set_max_transition 3 [get_ports {inf_D[47]}]
set_max_transition 3 [get_ports {inf_D[46]}]
set_max_transition 3 [get_ports {inf_D[45]}]
set_max_transition 3 [get_ports {inf_D[44]}]
set_max_transition 3 [get_ports {inf_D[43]}]
set_max_transition 3 [get_ports {inf_D[42]}]
set_max_transition 3 [get_ports {inf_D[41]}]
set_max_transition 3 [get_ports {inf_D[40]}]
set_max_transition 3 [get_ports {inf_D[39]}]
set_max_transition 3 [get_ports {inf_D[38]}]
set_max_transition 3 [get_ports {inf_D[37]}]
set_max_transition 3 [get_ports {inf_D[36]}]
set_max_transition 3 [get_ports {inf_D[35]}]
set_max_transition 3 [get_ports {inf_D[34]}]
set_max_transition 3 [get_ports {inf_D[33]}]
set_max_transition 3 [get_ports {inf_D[32]}]
set_max_transition 3 [get_ports {inf_D[31]}]
set_max_transition 3 [get_ports {inf_D[30]}]
set_max_transition 3 [get_ports {inf_D[29]}]
set_max_transition 3 [get_ports {inf_D[28]}]
set_max_transition 3 [get_ports {inf_D[27]}]
set_max_transition 3 [get_ports {inf_D[26]}]
set_max_transition 3 [get_ports {inf_D[25]}]
set_max_transition 3 [get_ports {inf_D[24]}]
set_max_transition 3 [get_ports {inf_D[23]}]
set_max_transition 3 [get_ports {inf_D[22]}]
set_max_transition 3 [get_ports {inf_D[21]}]
set_max_transition 3 [get_ports {inf_D[20]}]
set_max_transition 3 [get_ports {inf_D[19]}]
set_max_transition 3 [get_ports {inf_D[18]}]
set_max_transition 3 [get_ports {inf_D[17]}]
set_max_transition 3 [get_ports {inf_D[16]}]
set_max_transition 3 [get_ports {inf_D[15]}]
set_max_transition 3 [get_ports {inf_D[14]}]
set_max_transition 3 [get_ports {inf_D[13]}]
set_max_transition 3 [get_ports {inf_D[12]}]
set_max_transition 3 [get_ports {inf_D[11]}]
set_max_transition 3 [get_ports {inf_D[10]}]
set_max_transition 3 [get_ports {inf_D[9]}]
set_max_transition 3 [get_ports {inf_D[8]}]
set_max_transition 3 [get_ports {inf_D[7]}]
set_max_transition 3 [get_ports {inf_D[6]}]
set_max_transition 3 [get_ports {inf_D[5]}]
set_max_transition 3 [get_ports {inf_D[4]}]
set_max_transition 3 [get_ports {inf_D[3]}]
set_max_transition 3 [get_ports {inf_D[2]}]
set_max_transition 3 [get_ports {inf_D[1]}]
set_max_transition 3 [get_ports {inf_D[0]}]
set_max_transition 3 [get_ports inf_AR_READY]
set_max_transition 3 [get_ports inf_R_VALID]
set_max_transition 3 [get_ports {inf_R_RESP[1]}]
set_max_transition 3 [get_ports {inf_R_RESP[0]}]
set_max_transition 3 [get_ports {inf_R_DATA[63]}]
set_max_transition 3 [get_ports {inf_R_DATA[62]}]
set_max_transition 3 [get_ports {inf_R_DATA[61]}]
set_max_transition 3 [get_ports {inf_R_DATA[60]}]
set_max_transition 3 [get_ports {inf_R_DATA[59]}]
set_max_transition 3 [get_ports {inf_R_DATA[58]}]
set_max_transition 3 [get_ports {inf_R_DATA[57]}]
set_max_transition 3 [get_ports {inf_R_DATA[56]}]
set_max_transition 3 [get_ports {inf_R_DATA[55]}]
set_max_transition 3 [get_ports {inf_R_DATA[54]}]
set_max_transition 3 [get_ports {inf_R_DATA[53]}]
set_max_transition 3 [get_ports {inf_R_DATA[52]}]
set_max_transition 3 [get_ports {inf_R_DATA[51]}]
set_max_transition 3 [get_ports {inf_R_DATA[50]}]
set_max_transition 3 [get_ports {inf_R_DATA[49]}]
set_max_transition 3 [get_ports {inf_R_DATA[48]}]
set_max_transition 3 [get_ports {inf_R_DATA[47]}]
set_max_transition 3 [get_ports {inf_R_DATA[46]}]
set_max_transition 3 [get_ports {inf_R_DATA[45]}]
set_max_transition 3 [get_ports {inf_R_DATA[44]}]
set_max_transition 3 [get_ports {inf_R_DATA[43]}]
set_max_transition 3 [get_ports {inf_R_DATA[42]}]
set_max_transition 3 [get_ports {inf_R_DATA[41]}]
set_max_transition 3 [get_ports {inf_R_DATA[40]}]
set_max_transition 3 [get_ports {inf_R_DATA[39]}]
set_max_transition 3 [get_ports {inf_R_DATA[38]}]
set_max_transition 3 [get_ports {inf_R_DATA[37]}]
set_max_transition 3 [get_ports {inf_R_DATA[36]}]
set_max_transition 3 [get_ports {inf_R_DATA[35]}]
set_max_transition 3 [get_ports {inf_R_DATA[34]}]
set_max_transition 3 [get_ports {inf_R_DATA[33]}]
set_max_transition 3 [get_ports {inf_R_DATA[32]}]
set_max_transition 3 [get_ports {inf_R_DATA[31]}]
set_max_transition 3 [get_ports {inf_R_DATA[30]}]
set_max_transition 3 [get_ports {inf_R_DATA[29]}]
set_max_transition 3 [get_ports {inf_R_DATA[28]}]
set_max_transition 3 [get_ports {inf_R_DATA[27]}]
set_max_transition 3 [get_ports {inf_R_DATA[26]}]
set_max_transition 3 [get_ports {inf_R_DATA[25]}]
set_max_transition 3 [get_ports {inf_R_DATA[24]}]
set_max_transition 3 [get_ports {inf_R_DATA[23]}]
set_max_transition 3 [get_ports {inf_R_DATA[22]}]
set_max_transition 3 [get_ports {inf_R_DATA[21]}]
set_max_transition 3 [get_ports {inf_R_DATA[20]}]
set_max_transition 3 [get_ports {inf_R_DATA[19]}]
set_max_transition 3 [get_ports {inf_R_DATA[18]}]
set_max_transition 3 [get_ports {inf_R_DATA[17]}]
set_max_transition 3 [get_ports {inf_R_DATA[16]}]
set_max_transition 3 [get_ports {inf_R_DATA[15]}]
set_max_transition 3 [get_ports {inf_R_DATA[14]}]
set_max_transition 3 [get_ports {inf_R_DATA[13]}]
set_max_transition 3 [get_ports {inf_R_DATA[12]}]
set_max_transition 3 [get_ports {inf_R_DATA[11]}]
set_max_transition 3 [get_ports {inf_R_DATA[10]}]
set_max_transition 3 [get_ports {inf_R_DATA[9]}]
set_max_transition 3 [get_ports {inf_R_DATA[8]}]
set_max_transition 3 [get_ports {inf_R_DATA[7]}]
set_max_transition 3 [get_ports {inf_R_DATA[6]}]
set_max_transition 3 [get_ports {inf_R_DATA[5]}]
set_max_transition 3 [get_ports {inf_R_DATA[4]}]
set_max_transition 3 [get_ports {inf_R_DATA[3]}]
set_max_transition 3 [get_ports {inf_R_DATA[2]}]
set_max_transition 3 [get_ports {inf_R_DATA[1]}]
set_max_transition 3 [get_ports {inf_R_DATA[0]}]
set_max_transition 3 [get_ports inf_AW_READY]
set_max_transition 3 [get_ports inf_W_READY]
set_max_transition 3 [get_ports inf_B_VALID]
set_max_transition 3 [get_ports {inf_B_RESP[1]}]
set_max_transition 3 [get_ports {inf_B_RESP[0]}]
create_clock [get_ports clk]  -period 4.5  -waveform {0 2.25}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports inf_rst_n]
set_input_delay -clock clk  -max 2.25  [get_ports inf_sel_action_valid]
set_input_delay -clock clk  -min 0  [get_ports inf_sel_action_valid]
set_input_delay -clock clk  -max 2.25  [get_ports inf_type_valid]
set_input_delay -clock clk  -min 0  [get_ports inf_type_valid]
set_input_delay -clock clk  -max 2.25  [get_ports inf_mode_valid]
set_input_delay -clock clk  -min 0  [get_ports inf_mode_valid]
set_input_delay -clock clk  -max 2.25  [get_ports inf_date_valid]
set_input_delay -clock clk  -min 0  [get_ports inf_date_valid]
set_input_delay -clock clk  -max 2.25  [get_ports inf_staff_valid]
set_input_delay -clock clk  -min 0  [get_ports inf_staff_valid]
set_input_delay -clock clk  -max 2.25  [get_ports inf_data_no_valid]
set_input_delay -clock clk  -min 0  [get_ports inf_data_no_valid]
set_input_delay -clock clk  -max 2.25  [get_ports inf_restock_valid]
set_input_delay -clock clk  -min 0  [get_ports inf_restock_valid]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[71]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[71]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[70]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[70]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[69]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[69]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[68]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[68]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[67]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[67]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[66]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[66]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[65]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[65]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[64]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[64]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[63]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[63]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[62]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[62]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[61]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[61]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[60]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[60]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[59]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[59]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[58]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[58]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[57]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[57]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[56]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[56]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[55]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[55]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[54]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[54]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[53]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[53]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[52]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[52]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[51]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[51]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[50]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[50]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[49]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[49]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[48]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[48]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[47]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[47]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[46]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[46]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[45]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[45]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[44]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[44]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[43]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[43]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[42]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[42]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[41]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[41]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[40]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[40]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[39]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[39]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[38]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[38]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[37]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[37]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[36]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[36]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[35]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[35]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[34]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[34]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[33]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[33]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[32]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[32]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[31]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[31]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[30]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[30]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[29]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[29]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[28]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[28]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[27]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[27]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[26]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[26]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[25]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[25]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[24]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[24]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[23]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[23]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[22]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[22]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[21]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[21]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[20]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[20]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[19]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[19]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[18]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[18]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[17]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[17]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[16]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[16]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[15]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[15]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[14]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[14]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[13]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[13]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[12]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[12]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[11]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[11]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[10]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[10]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[9]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[9]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[8]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[8]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[7]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[7]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[6]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[6]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[5]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[5]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[4]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[4]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[3]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[3]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[2]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[2]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[1]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[1]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_D[0]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_D[0]}]
set_input_delay -clock clk  -max 2.25  [get_ports inf_AR_READY]
set_input_delay -clock clk  -min 0  [get_ports inf_AR_READY]
set_input_delay -clock clk  -max 2.25  [get_ports inf_R_VALID]
set_input_delay -clock clk  -min 0  [get_ports inf_R_VALID]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_RESP[1]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_RESP[1]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_RESP[0]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_RESP[0]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[63]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[63]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[62]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[62]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[61]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[61]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[60]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[60]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[59]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[59]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[58]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[58]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[57]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[57]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[56]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[56]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[55]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[55]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[54]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[54]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[53]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[53]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[52]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[52]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[51]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[51]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[50]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[50]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[49]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[49]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[48]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[48]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[47]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[47]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[46]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[46]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[45]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[45]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[44]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[44]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[43]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[43]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[42]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[42]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[41]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[41]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[40]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[40]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[39]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[39]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[38]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[38]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[37]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[37]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[36]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[36]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[35]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[35]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[34]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[34]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[33]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[33]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[32]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[32]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[31]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[31]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[30]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[30]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[29]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[29]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[28]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[28]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[27]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[27]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[26]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[26]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[25]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[25]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[24]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[24]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[23]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[23]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[22]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[22]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[21]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[21]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[20]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[20]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[19]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[19]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[18]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[18]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[17]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[17]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[16]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[16]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[15]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[15]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[14]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[14]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[13]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[13]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[12]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[12]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[11]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[11]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[10]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[10]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[9]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[9]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[8]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[8]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[7]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[7]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[6]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[6]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[5]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[5]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[4]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[4]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[3]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[3]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[2]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[2]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[1]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[1]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_R_DATA[0]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_R_DATA[0]}]
set_input_delay -clock clk  -max 2.25  [get_ports inf_AW_READY]
set_input_delay -clock clk  -min 0  [get_ports inf_AW_READY]
set_input_delay -clock clk  -max 2.25  [get_ports inf_W_READY]
set_input_delay -clock clk  -min 0  [get_ports inf_W_READY]
set_input_delay -clock clk  -max 2.25  [get_ports inf_B_VALID]
set_input_delay -clock clk  -min 0  [get_ports inf_B_VALID]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_B_RESP[1]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_B_RESP[1]}]
set_input_delay -clock clk  -max 2.25  [get_ports {inf_B_RESP[0]}]
set_input_delay -clock clk  -min 0  [get_ports {inf_B_RESP[0]}]
set_output_delay -clock clk  -max 2.25  [get_ports inf_out_valid]
set_output_delay -clock clk  -min 0  [get_ports inf_out_valid]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_warn_msg[2]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_warn_msg[2]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_warn_msg[1]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_warn_msg[1]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_warn_msg[0]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_warn_msg[0]}]
set_output_delay -clock clk  -max 2.25  [get_ports inf_complete]
set_output_delay -clock clk  -min 0  [get_ports inf_complete]
set_output_delay -clock clk  -max 2.25  [get_ports inf_AR_VALID]
set_output_delay -clock clk  -min 0  [get_ports inf_AR_VALID]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[16]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[16]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[15]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[15]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[14]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[14]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[13]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[13]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[12]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[12]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[11]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[11]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[10]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[10]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[9]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[9]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[8]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[8]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[7]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[7]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[6]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[6]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[5]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[5]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[4]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[4]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[3]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[3]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[2]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[2]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[1]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[1]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AR_ADDR[0]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AR_ADDR[0]}]
set_output_delay -clock clk  -max 2.25  [get_ports inf_R_READY]
set_output_delay -clock clk  -min 0  [get_ports inf_R_READY]
set_output_delay -clock clk  -max 2.25  [get_ports inf_AW_VALID]
set_output_delay -clock clk  -min 0  [get_ports inf_AW_VALID]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[16]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[16]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[15]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[15]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[14]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[14]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[13]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[13]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[12]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[12]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[11]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[11]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[10]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[10]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[9]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[9]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[8]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[8]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[7]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[7]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[6]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[6]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[5]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[5]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[4]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[4]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[3]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[3]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[2]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[2]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[1]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[1]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_AW_ADDR[0]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_AW_ADDR[0]}]
set_output_delay -clock clk  -max 2.25  [get_ports inf_W_VALID]
set_output_delay -clock clk  -min 0  [get_ports inf_W_VALID]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[63]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[63]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[62]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[62]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[61]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[61]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[60]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[60]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[59]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[59]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[58]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[58]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[57]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[57]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[56]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[56]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[55]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[55]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[54]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[54]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[53]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[53]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[52]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[52]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[51]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[51]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[50]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[50]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[49]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[49]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[48]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[48]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[47]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[47]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[46]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[46]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[45]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[45]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[44]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[44]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[43]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[43]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[42]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[42]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[41]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[41]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[40]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[40]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[39]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[39]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[38]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[38]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[37]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[37]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[36]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[36]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[35]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[35]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[34]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[34]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[33]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[33]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[32]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[32]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[31]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[31]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[30]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[30]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[29]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[29]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[28]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[28]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[27]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[27]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[26]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[26]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[25]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[25]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[24]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[24]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[23]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[23]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[22]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[22]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[21]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[21]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[20]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[20]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[19]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[19]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[18]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[18]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[17]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[17]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[16]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[16]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[15]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[15]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[14]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[14]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[13]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[13]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[12]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[12]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[11]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[11]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[10]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[10]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[9]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[9]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[8]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[8]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[7]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[7]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[6]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[6]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[5]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[5]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[4]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[4]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[3]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[3]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[2]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[2]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[1]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[1]}]
set_output_delay -clock clk  -max 2.25  [get_ports {inf_W_DATA[0]}]
set_output_delay -clock clk  -min 0  [get_ports {inf_W_DATA[0]}]
set_output_delay -clock clk  -max 2.25  [get_ports inf_B_READY]
set_output_delay -clock clk  -min 0  [get_ports inf_B_READY]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports inf_rst_n]
set_input_transition -min 0.5  [get_ports inf_rst_n]
set_input_transition -max 0.5  [get_ports inf_sel_action_valid]
set_input_transition -min 0.5  [get_ports inf_sel_action_valid]
set_input_transition -max 0.5  [get_ports inf_type_valid]
set_input_transition -min 0.5  [get_ports inf_type_valid]
set_input_transition -max 0.5  [get_ports inf_mode_valid]
set_input_transition -min 0.5  [get_ports inf_mode_valid]
set_input_transition -max 0.5  [get_ports inf_date_valid]
set_input_transition -min 0.5  [get_ports inf_date_valid]
set_input_transition -max 0.5  [get_ports inf_staff_valid]
set_input_transition -min 0.5  [get_ports inf_staff_valid]
set_input_transition -max 0.5  [get_ports inf_data_no_valid]
set_input_transition -min 0.5  [get_ports inf_data_no_valid]
set_input_transition -max 0.5  [get_ports inf_restock_valid]
set_input_transition -min 0.5  [get_ports inf_restock_valid]
set_input_transition -max 0.5  [get_ports {inf_D[71]}]
set_input_transition -min 0.5  [get_ports {inf_D[71]}]
set_input_transition -max 0.5  [get_ports {inf_D[70]}]
set_input_transition -min 0.5  [get_ports {inf_D[70]}]
set_input_transition -max 0.5  [get_ports {inf_D[69]}]
set_input_transition -min 0.5  [get_ports {inf_D[69]}]
set_input_transition -max 0.5  [get_ports {inf_D[68]}]
set_input_transition -min 0.5  [get_ports {inf_D[68]}]
set_input_transition -max 0.5  [get_ports {inf_D[67]}]
set_input_transition -min 0.5  [get_ports {inf_D[67]}]
set_input_transition -max 0.5  [get_ports {inf_D[66]}]
set_input_transition -min 0.5  [get_ports {inf_D[66]}]
set_input_transition -max 0.5  [get_ports {inf_D[65]}]
set_input_transition -min 0.5  [get_ports {inf_D[65]}]
set_input_transition -max 0.5  [get_ports {inf_D[64]}]
set_input_transition -min 0.5  [get_ports {inf_D[64]}]
set_input_transition -max 0.5  [get_ports {inf_D[63]}]
set_input_transition -min 0.5  [get_ports {inf_D[63]}]
set_input_transition -max 0.5  [get_ports {inf_D[62]}]
set_input_transition -min 0.5  [get_ports {inf_D[62]}]
set_input_transition -max 0.5  [get_ports {inf_D[61]}]
set_input_transition -min 0.5  [get_ports {inf_D[61]}]
set_input_transition -max 0.5  [get_ports {inf_D[60]}]
set_input_transition -min 0.5  [get_ports {inf_D[60]}]
set_input_transition -max 0.5  [get_ports {inf_D[59]}]
set_input_transition -min 0.5  [get_ports {inf_D[59]}]
set_input_transition -max 0.5  [get_ports {inf_D[58]}]
set_input_transition -min 0.5  [get_ports {inf_D[58]}]
set_input_transition -max 0.5  [get_ports {inf_D[57]}]
set_input_transition -min 0.5  [get_ports {inf_D[57]}]
set_input_transition -max 0.5  [get_ports {inf_D[56]}]
set_input_transition -min 0.5  [get_ports {inf_D[56]}]
set_input_transition -max 0.5  [get_ports {inf_D[55]}]
set_input_transition -min 0.5  [get_ports {inf_D[55]}]
set_input_transition -max 0.5  [get_ports {inf_D[54]}]
set_input_transition -min 0.5  [get_ports {inf_D[54]}]
set_input_transition -max 0.5  [get_ports {inf_D[53]}]
set_input_transition -min 0.5  [get_ports {inf_D[53]}]
set_input_transition -max 0.5  [get_ports {inf_D[52]}]
set_input_transition -min 0.5  [get_ports {inf_D[52]}]
set_input_transition -max 0.5  [get_ports {inf_D[51]}]
set_input_transition -min 0.5  [get_ports {inf_D[51]}]
set_input_transition -max 0.5  [get_ports {inf_D[50]}]
set_input_transition -min 0.5  [get_ports {inf_D[50]}]
set_input_transition -max 0.5  [get_ports {inf_D[49]}]
set_input_transition -min 0.5  [get_ports {inf_D[49]}]
set_input_transition -max 0.5  [get_ports {inf_D[48]}]
set_input_transition -min 0.5  [get_ports {inf_D[48]}]
set_input_transition -max 0.5  [get_ports {inf_D[47]}]
set_input_transition -min 0.5  [get_ports {inf_D[47]}]
set_input_transition -max 0.5  [get_ports {inf_D[46]}]
set_input_transition -min 0.5  [get_ports {inf_D[46]}]
set_input_transition -max 0.5  [get_ports {inf_D[45]}]
set_input_transition -min 0.5  [get_ports {inf_D[45]}]
set_input_transition -max 0.5  [get_ports {inf_D[44]}]
set_input_transition -min 0.5  [get_ports {inf_D[44]}]
set_input_transition -max 0.5  [get_ports {inf_D[43]}]
set_input_transition -min 0.5  [get_ports {inf_D[43]}]
set_input_transition -max 0.5  [get_ports {inf_D[42]}]
set_input_transition -min 0.5  [get_ports {inf_D[42]}]
set_input_transition -max 0.5  [get_ports {inf_D[41]}]
set_input_transition -min 0.5  [get_ports {inf_D[41]}]
set_input_transition -max 0.5  [get_ports {inf_D[40]}]
set_input_transition -min 0.5  [get_ports {inf_D[40]}]
set_input_transition -max 0.5  [get_ports {inf_D[39]}]
set_input_transition -min 0.5  [get_ports {inf_D[39]}]
set_input_transition -max 0.5  [get_ports {inf_D[38]}]
set_input_transition -min 0.5  [get_ports {inf_D[38]}]
set_input_transition -max 0.5  [get_ports {inf_D[37]}]
set_input_transition -min 0.5  [get_ports {inf_D[37]}]
set_input_transition -max 0.5  [get_ports {inf_D[36]}]
set_input_transition -min 0.5  [get_ports {inf_D[36]}]
set_input_transition -max 0.5  [get_ports {inf_D[35]}]
set_input_transition -min 0.5  [get_ports {inf_D[35]}]
set_input_transition -max 0.5  [get_ports {inf_D[34]}]
set_input_transition -min 0.5  [get_ports {inf_D[34]}]
set_input_transition -max 0.5  [get_ports {inf_D[33]}]
set_input_transition -min 0.5  [get_ports {inf_D[33]}]
set_input_transition -max 0.5  [get_ports {inf_D[32]}]
set_input_transition -min 0.5  [get_ports {inf_D[32]}]
set_input_transition -max 0.5  [get_ports {inf_D[31]}]
set_input_transition -min 0.5  [get_ports {inf_D[31]}]
set_input_transition -max 0.5  [get_ports {inf_D[30]}]
set_input_transition -min 0.5  [get_ports {inf_D[30]}]
set_input_transition -max 0.5  [get_ports {inf_D[29]}]
set_input_transition -min 0.5  [get_ports {inf_D[29]}]
set_input_transition -max 0.5  [get_ports {inf_D[28]}]
set_input_transition -min 0.5  [get_ports {inf_D[28]}]
set_input_transition -max 0.5  [get_ports {inf_D[27]}]
set_input_transition -min 0.5  [get_ports {inf_D[27]}]
set_input_transition -max 0.5  [get_ports {inf_D[26]}]
set_input_transition -min 0.5  [get_ports {inf_D[26]}]
set_input_transition -max 0.5  [get_ports {inf_D[25]}]
set_input_transition -min 0.5  [get_ports {inf_D[25]}]
set_input_transition -max 0.5  [get_ports {inf_D[24]}]
set_input_transition -min 0.5  [get_ports {inf_D[24]}]
set_input_transition -max 0.5  [get_ports {inf_D[23]}]
set_input_transition -min 0.5  [get_ports {inf_D[23]}]
set_input_transition -max 0.5  [get_ports {inf_D[22]}]
set_input_transition -min 0.5  [get_ports {inf_D[22]}]
set_input_transition -max 0.5  [get_ports {inf_D[21]}]
set_input_transition -min 0.5  [get_ports {inf_D[21]}]
set_input_transition -max 0.5  [get_ports {inf_D[20]}]
set_input_transition -min 0.5  [get_ports {inf_D[20]}]
set_input_transition -max 0.5  [get_ports {inf_D[19]}]
set_input_transition -min 0.5  [get_ports {inf_D[19]}]
set_input_transition -max 0.5  [get_ports {inf_D[18]}]
set_input_transition -min 0.5  [get_ports {inf_D[18]}]
set_input_transition -max 0.5  [get_ports {inf_D[17]}]
set_input_transition -min 0.5  [get_ports {inf_D[17]}]
set_input_transition -max 0.5  [get_ports {inf_D[16]}]
set_input_transition -min 0.5  [get_ports {inf_D[16]}]
set_input_transition -max 0.5  [get_ports {inf_D[15]}]
set_input_transition -min 0.5  [get_ports {inf_D[15]}]
set_input_transition -max 0.5  [get_ports {inf_D[14]}]
set_input_transition -min 0.5  [get_ports {inf_D[14]}]
set_input_transition -max 0.5  [get_ports {inf_D[13]}]
set_input_transition -min 0.5  [get_ports {inf_D[13]}]
set_input_transition -max 0.5  [get_ports {inf_D[12]}]
set_input_transition -min 0.5  [get_ports {inf_D[12]}]
set_input_transition -max 0.5  [get_ports {inf_D[11]}]
set_input_transition -min 0.5  [get_ports {inf_D[11]}]
set_input_transition -max 0.5  [get_ports {inf_D[10]}]
set_input_transition -min 0.5  [get_ports {inf_D[10]}]
set_input_transition -max 0.5  [get_ports {inf_D[9]}]
set_input_transition -min 0.5  [get_ports {inf_D[9]}]
set_input_transition -max 0.5  [get_ports {inf_D[8]}]
set_input_transition -min 0.5  [get_ports {inf_D[8]}]
set_input_transition -max 0.5  [get_ports {inf_D[7]}]
set_input_transition -min 0.5  [get_ports {inf_D[7]}]
set_input_transition -max 0.5  [get_ports {inf_D[6]}]
set_input_transition -min 0.5  [get_ports {inf_D[6]}]
set_input_transition -max 0.5  [get_ports {inf_D[5]}]
set_input_transition -min 0.5  [get_ports {inf_D[5]}]
set_input_transition -max 0.5  [get_ports {inf_D[4]}]
set_input_transition -min 0.5  [get_ports {inf_D[4]}]
set_input_transition -max 0.5  [get_ports {inf_D[3]}]
set_input_transition -min 0.5  [get_ports {inf_D[3]}]
set_input_transition -max 0.5  [get_ports {inf_D[2]}]
set_input_transition -min 0.5  [get_ports {inf_D[2]}]
set_input_transition -max 0.5  [get_ports {inf_D[1]}]
set_input_transition -min 0.5  [get_ports {inf_D[1]}]
set_input_transition -max 0.5  [get_ports {inf_D[0]}]
set_input_transition -min 0.5  [get_ports {inf_D[0]}]
set_input_transition -max 0.5  [get_ports inf_AR_READY]
set_input_transition -min 0.5  [get_ports inf_AR_READY]
set_input_transition -max 0.5  [get_ports inf_R_VALID]
set_input_transition -min 0.5  [get_ports inf_R_VALID]
set_input_transition -max 0.5  [get_ports {inf_R_RESP[1]}]
set_input_transition -min 0.5  [get_ports {inf_R_RESP[1]}]
set_input_transition -max 0.5  [get_ports {inf_R_RESP[0]}]
set_input_transition -min 0.5  [get_ports {inf_R_RESP[0]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[63]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[63]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[62]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[62]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[61]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[61]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[60]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[60]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[59]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[59]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[58]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[58]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[57]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[57]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[56]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[56]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[55]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[55]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[54]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[54]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[53]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[53]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[52]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[52]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[51]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[51]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[50]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[50]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[49]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[49]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[48]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[48]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[47]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[47]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[46]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[46]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[45]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[45]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[44]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[44]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[43]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[43]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[42]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[42]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[41]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[41]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[40]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[40]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[39]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[39]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[38]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[38]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[37]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[37]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[36]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[36]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[35]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[35]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[34]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[34]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[33]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[33]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[32]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[32]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[31]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[31]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[30]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[30]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[29]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[29]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[28]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[28]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[27]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[27]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[26]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[26]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[25]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[25]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[24]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[24]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[23]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[23]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[22]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[22]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[21]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[21]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[20]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[20]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[19]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[19]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[18]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[18]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[17]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[17]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[16]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[16]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[15]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[15]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[14]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[14]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[13]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[13]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[12]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[12]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[11]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[11]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[10]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[10]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[9]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[9]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[8]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[8]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[7]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[7]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[6]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[6]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[5]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[5]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[4]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[4]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[3]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[3]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[2]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[2]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[1]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[1]}]
set_input_transition -max 0.5  [get_ports {inf_R_DATA[0]}]
set_input_transition -min 0.5  [get_ports {inf_R_DATA[0]}]
set_input_transition -max 0.5  [get_ports inf_AW_READY]
set_input_transition -min 0.5  [get_ports inf_AW_READY]
set_input_transition -max 0.5  [get_ports inf_W_READY]
set_input_transition -min 0.5  [get_ports inf_W_READY]
set_input_transition -max 0.5  [get_ports inf_B_VALID]
set_input_transition -min 0.5  [get_ports inf_B_VALID]
set_input_transition -max 0.5  [get_ports {inf_B_RESP[1]}]
set_input_transition -min 0.5  [get_ports {inf_B_RESP[1]}]
set_input_transition -max 0.5  [get_ports {inf_B_RESP[0]}]
set_input_transition -min 0.5  [get_ports {inf_B_RESP[0]}]
